### ISSUE TITLE
Creating ANSI C compiler

### ISSUE THREAD

**Issue by SuperJMN** [orangeduck/mpc#104]
Hello! Congratulations of this great piece of software. I'm very interested in parser combinators and I would like to create something like an ANSI C compiler.

I'm almost sure it's not an easy task. I've already tried to translate a grammar to a parse combinator library, like this one.

Mainly, I have problems with productions like this:

```
<postfix-expression> ::= <primary-expression>
                       | <postfix-expression> [ <expression> ]
                       | <postfix-expression> ( {<assignment-expression>}* )
                       | <postfix-expression> . <identifier>
                       | <postfix-expression> -> <identifier>
                       | <postfix-expression> ++
                       | <postfix-expression> --
```

I don't have a clue on how to translate it.

I'm sure it has to be transformed to avoid the left recursion, but my brain explodes. I hope you can shed some light and help me.

Big thanks in advance!

The grammar I'm following is this one: http://www.quut.com/c/ANSI-C-grammar-y.html

**Comment by orangeduck** [comment]
Hi SuperJMN,

Great project!

Yes something like that will definitely need to be adjusted to avoid left recursion. I'm not sure there is any kind of simple procedure you can follow that will always avoid left recursion but the wikipedia page actually has some suprisingly useful tips:

https://en.wikipedia.org/wiki/Left_recursion#Removing_left_recursion

The basic two techniques that helped me get a kind of intuition for producing "safe" grammars are:

1. factorization - extracting common subexpressions inside big "or" clauses as much as possible.
2. looping instead of recursion - try to transform recursive rules to use the + or * combinators instead.

For example, I may be wrong but I think the example you showed can be re-written to remove the recursion using the * combinator instead and an additional rule.

```
<postfix-op> ::= [ <expression> ]
                       | ( {<assignment-expression>}* )
                       | . <identifier>
                       | -> <identifier>
                       | ++
                       | --
                       ;
<postfix-expression> ::= <primary-expression> <postfix-op>*;
```

Hope that helps,

Dan

**Comment by SuperJMN** [comment]
Thanks for your response and happy new year! I'll try your attempt. The problem mainly comes when there's indirect left recursion, that is hard to detect.

BTW, I've found this great publication. Maybe it's worth a read. In theory, it would enable to define some operators that could deal with this kind of problem. The problem? I don't know Haskell. 
http://richard.myweb.cs.uwindsor.ca/PUBLICATIONS/PADL_08.pdf

Hopefully you could interpret it better than me :)

Keep up the good work!

**Comment by orangeduck** [comment]
Yes - I heard that publication was quite a breakthrough and it would be great to add it to mpc but I'd probably have to look into it in a lot more depth to see how possible it is to do in C. Thanks!
