### ISSUE TITLE
`malloc`casts & `realloc` checks?

### ISSUE THREAD

**Issue by hellerve** [orangeduck/mpc#21]
I am using currently using your (awesome) project for a doodle of mine. While browsing through it and giving rewriting a shot(for my understanding of it and to fit into my personal coding style), I saw that you do not cast `malloc` and the like to the appropriate pointer types, which does not play well with the picky extensions I am normally using. There's a few more occurrences of missing casting(namely when using `sizeof`). Should I go and create a pull request for this or do you deem casts as too ugly?

Also, you are not checking the return value of `realloc`. Fair enough, but I rewrote that to at least check it in the `mpc_stack_parsers_reserve_*` functions, where failing to allocate more memory could happen. Should I create a pull request for that, too?

**Comment by orangeduck** [comment]
Hey,

Thanks! Of course it is perseonal preference, but I think in C typically you [don't cast the result of malloc](http://stackoverflow.com/questions/605845/do-i-cast-the-result-of-malloc), although this is needed in C++ and also I understand if various extensions or whatever require you to cast the result. Casts from sizeof etc could be a problem but it depends on the context. I think in general I'd rather do without any non-essential casts for the main repo as I think it can clutter the code.

Probably I should be checking the return value of `realloc`/`malloc` as you're right - the parser could run out of memory if it goes into an infinite loop - and people might be using this on smaller embedded systems. So if you feel like making a pull request for that, that would be cool.

Although I think in practice checking the return value of `malloc`/`realloc` is often [pretty useless]( http://stackoverflow.com/questions/1941323/always-check-malloced-memory). And you have to be careful because `realloc` can return NULL in two cases - either if out of memory of if (much more likely) you request to resize to 0 bytes. This always comes up for dynamically sized arrays because when you pop all the items they return to size zero.

Thanks,

Dam

**Comment by hellerve** [comment]
Hey,

thanks for the in-depth insight. Of course all your points are valid. As long as it's an informed decision, I'm down with every of your design choices. Just keep in mind that users of extremely picky makefile templates like me(with `pedantic` always switched on) might run into problems(although I cannot recall which extension specifically broke compiling).

Cheers
