### ISSUE TITLE
Segfault on parse error

### ISSUE THREAD

**Issue by mikebolt** [orangeduck/mpc#23]
I wrote the following simple test program, test.c:

    #include <stdio.h>
    #include "mpc/mpc.h"

    int main(int argc, char **argv) {
       mpc_result_t result;

       if (argc != 2) {
          fprintf(stderr, "Usage: test filename\n");
          exit(1);
       }

       mpc_parser_t *asdf = mpc_new("asdf");
       mpc_parser_t *jkl = mpc_new("jkl");
       mpc_parser_t *line = mpc_new("line");
       mpc_parser_t *braceLine = mpc_new("braceLine");
       mpc_parser_t *program = mpc_new("program");

       mpca_lang(MPCA_LANG_DEFAULT,
          "asdf : \"asdf\";"
          "jkl : \"jkl;\";"
          "line : <asdf>* <jkl>;"
          "braceLine : <line> | ('{' <program> '}');"
          "program : <braceLine>*;",
          asdf, jkl, line, braceLine, program, NULL);

       if (mpc_parse_contents(argv[1], program, &result)) {
          mpc_ast_print(result.output);
          mpc_ast_delete(result.output);
       }
       else {
          fprintf(stderr, "Error!\n");

          mpc_err_print(result.error);
          mpc_err_delete(result.error);
       }

       mpc_cleanup(5, asdf, jkl, line, braceLine, program);

       return 0;
    }

This program runs correctly when the input is valid, and crashes with a segfault when the input is invalid, before reaching the "Error!" fprintf, so the segfault is in mpc_parse_contents. I ran gdb and got the following result:

    Program received signal SIGSEGV, Segmentation fault.
    0x080502c3 in mpc_ast_print_depth (a=0x0, d=0, fp=0xb374e0) at mpc/mpc.c:2604
    2604      if (strlen(a->contents)) {

Let me know if you need any more information.

**Comment by orangeduck** [comment]
Thanks for the report! This should be fixed in 3878cd76e6de75d4427219c823947fac19a29a4f, perhaps you can verify. You should note that this is due to the result of the parse being `NULL` as your rule `program : <braceLine>*;` will match the empty string (due to wanting _zero_ or more braceLine) and return no syntax tree. So if you are going to do some processing on the result of this parse make sure you check for `NULL` and don't just assume the returned ast is valid (as I did).
