### ISSUE TITLE
Uninuitive behaviour of stripping parsers?

### ISSUE THREAD

**Issue by Wyatts** [orangeduck/mpc#25]
I'm trying to replace an awful pile of buggy (legacy) regex hacks with a proper parser, and I hit an odd situation.  Consider the following minimal example:

        mpc_result_t r;
        mpc_parser_t *comment = mpc_many(mpcf_strfold, mpc_noneof("*#"));
        char *input = strdup("not a #comment");
        if(mpc_parse("input", input, comment, &r)) {
                printf("\"%s\"\n", r.output); // Quoting to display whitespace bounds
        } else { mpc_err_print(r.error); mpc_err_delete(r.error); }

That works, but leaves behind any space between the end of the statement and the beginning of the comment.  I thought I could simply remove them with one of the provided parsers, but they don't seem to work as I'd expect.  I tried this first:

    mpc_parser_t *comment = mpc_stripr(mpc_many(mpcf_strfold, mpc_noneof("*#")));

...and then the same with mpc_strip() and mpc_tok(), but the output continues to be

    "not a "

I don't know if this is just a doc bug or a library bug or what, but something certainly _feels_ wrong here.  What can we do about it?

**Comment by orangeduck** [comment]
Hi Wyatts,

Thanks for the error report. You've stumbled upon an interesting case here and it definitely took me a second to work out what the hell was going on. The reason it behaves as it does is due to how the functions `mpc_strip` etc work. For example the function `mpc_stripl` returns a parser that first consumes zero or more whitespace characters, _then_ runs the parser you give it as input, and returns the result of that. They don't actually run the parser you give them _then_ strip it of whitespace. So the parser found by `mpc_stripr` was running your parser, then running a parser that stripped whitespace to the right (which found no whitespace since it was the end of the string), and then returning the result of your parser.

The reason for this behaviour rather than the one you expected is for two reasons. First - you can give them parsers which don't include the whitespace capture themselves, and second - they can be used on conjunction with parsers that don't return strings. Although I appreciate how incredibly confusing the names and documentation are.

If you give me a few days I'll push up an update with some functions `mpcf_strstrip`, `mpcf_strstripl`, `mpcf_strstripr` which could be passed to `mpc_apply` to get the behaviour you want. I'll also try to update the documentation to make it a bit clearer :+1: 

Thanks,

Dan

**Comment by Wyatts** [comment]
Oh wow, that's...yeah, that's really far from what I expected, haha.  But this all sounds great.  A few days?  I can wait that long, for sure!  I tried cobbling together something that did what I expected, but I'm pretty new to the combinator approach, and it turns out to be fairly hard to reason about when you have an incomplete understanding of the library.  (More short examples that demonstrate how to _accomplish things_ would be awesome, though that's out of scope for this issue.)

**Comment by orangeduck** [comment]
Well the basic idea is this - you should use `mpc_apply` with a function that takes as input some string and returns that string stripped. You could start from something like this:

http://stackoverflow.com/questions/122616/how-do-i-trim-leading-trailing-whitespace-in-a-standard-way

Then instead of

```
mpc_parser_t *comment = mpc_stripr(mpc_many(mpcf_strfold, mpc_noneof("*#")));
```

You pass the function to `mpc_apply` which will _apply_ it to the result of the parse as you were expecting.

```
mpc_parser_t *comment = mpc_apply(mpc_many(mpcf_strfold, mpc_noneof("*#")), stripping_function);
```

You're right about the examples. I'll have to put some together.

**Comment by orangeduck** [comment]
Hey,

You can try commit 6a8dc2e3f96fdee22db64256165b945ecc16bfda with the code:

```
mpc_parser_t *comment = mpc_apply(mpc_many(mpcf_strfold, mpc_noneof("*#")), mpcf_strtrimr);
```

Thanks,

Dan

**Comment by Wyatts** [comment]
I can totally live with "a few days" meaning "fifteen hours" in this case. ;)  That indeed does the trick, thanks!

And this all gives me some important clues, too: you can probably tell from my attempted sample, but I was thinking in terms each successive parser in the chain lowering the output of the prior.  But actually, it's more like each successive parser is applied to the remainder of the input that wasn't consumed by the one preceding it, and the resultant output of each parser capture is arbitrated by the fold function.  So using this library is likely to involve some amount of custom folds and utility functions for in situ transformations via mpc_apply().  (I think.)

Anyway, I'm satisfied.  (I'll leave you to close it at your discretion; I tend to keep things open until I've documented them, but that's because I'll forget without that anchor there.)

**Comment by orangeduck** [comment]
No problem, managed to find some free time this morning :+1: 

Yeah that is exactly correct. If you don't want to do all of the applying and folding you can use the grammar method (via `mpca_lang`) and process the AST afterwards, but otherwise doing that stuff is unavoidable.

Thanks,

Dan
