### ISSUE TITLE
Regex difficulty with adding decimal support

### ISSUE THREAD

**Issue by judepayne** [orangeduck/mpc#29]
Hi,
first of all thanks for your wonderful book!
I am having difficulty adding support for doubles and wondered if you could offer any tips?
I've added a parser for doubles and all the rest of the plumbing as per number but can't seem to get past the first stage, defining the reggae for the parser:
mpca_lang(MPCA_LANG_DEFAULT,
		"													\
		number    : /-?[0-9]+/ ;							\
		doub      : /-?[0-9]+\\.[0-9]+/ ;                   \
		symbol    : \"list\" | \"head\" | \"tail\"      	\
				  | \"join\" | \"eval\"	| \"len\"			\
...
I also get the following error message when typing in say '1.0' into my interpreter. 
:1:2: error: expected one of '0123456789', whitespace, '-', one or more of one of '0123456789', "list", "head", "tail", "join", "eval", "len", "cons", "init", '+', '*', '/', '(', '{' or end of input at '.'
thanks in advance,
Jude

**Comment by orangeduck** [comment]
Hi Jude,

Probably all you need to do is escape the `.` character twice (because it is inside a C string) so it looks like `\\.`. There are a couple of other people who had the same issue that you can look at:

https://github.com/orangeduck/mpc/issues/12
https://github.com/orangeduck/mpc/issues/10

Thanks,

Dan

**Comment by judepayne** [comment]
Thank you. silly error. I had omitted to include in the expr list. adding .. solved it.
		expr      : <doub> | <number> | <symbol> | <sexpr>  \
				  | <qexpr>;								\
