### ISSUE TITLE
Parser acting unexpectedly.

### ISSUE THREAD

**Issue by VitorCBSB** [orangeduck/mpc#33]
Hello, I've been trying to learn to use this library for a personal project so this problem is probably just a result of this learning process, but it's had me scratching my head for a while now.

I modified the maths.c example to the following grammar:

```c
...
mpc_parser_t *New_Expr = mpc_new("new_expr");

mpca_lang(MPCA_LANG_PREDICTIVE,
    " expression : <product> (('+' | '-') <product>)*;                                                 "
    " product : <value>   (('*' | '/')   <value>)*;                                                    "
    " value : /[0-9]+/ | <new_expr> | \"repeat\" | \"rand\" | \"sin\" <new_expr> | \"cos\" <new_expr>; "
    " new_expr : '(' <expression> ')';                                                                 "
    " maths : /^/ <expression> /$/;                                                                    ",
    Expr, Prod, Value, Maths, New_Expr, NULL);
...
mpc_cleanup(5, Expr, Prod, Value, Maths, New_Expr);

```

That is, I added a few more valid values (`repeat, rand, sin <new_expr>, cos <new_expr>`) and added a new rule `new_expr`.

It works correctly for inputs that contain `repeat`, such as `1 + 2 + repeat`, but doesn't work for others such as `1 + 2 + rand`. I have no idea why this is happening. The error message (for the second expression) reads:

`test.txt:1:10: error: expected "repeat", "rand", "sin", "cos" or end of input at 'a'`

Thanks in advance.

**Comment by orangeduck** [comment]
That is really weird. I'll have to investigate more and see what is wrong.

**Comment by orangeduck** [comment]
I found the problem. The issue is that you are declaring your grammar as predictive: `MPCA_LANG_PREDICTIVE`.

Predictive means that no backtracking is required and that the first character any of the cases of an _or_ clause always informs how the whole clause is going to be parsed. This is good for performance reasons but can't always be ensured for every grammar.

When you added `repeat` and `rand` it meant your grammar was no longer predictive because because both of them start with `r`. So the parser first tries to parse `repeat` and gets the first `r` and fails - at this point it needs to backtrack if it wants to parse `rand` but it doesn't bother because it is delcared as `predictive` and carries on blindly trying to parse the next `a`.

Probably I should remove the `MPCA_LANG_PREDICTIVE` clause from the maths example to give people a better starting point - and also consider throwing some sort of error when a predictive grammar is asked to backtrack.

Hope that helps,

- Dan

**Comment by VitorCBSB** [comment]
Yes, changing it to `MPCA_LANG_DEFAULT` makes it work as expected. I assume this is the one I should be using? In any case, thank you very much for your help. :)

**Comment by orangeduck** [comment]
Yup, `MPCA_LANG_DEFAULT` is correct. No problem, and good luck with your project.
