### ISSUE TITLE
Probably  bugs

### ISSUE THREAD

**Issue by yihuang** [orangeduck/mpc#42]
Please check out my gist:
https://gist.github.com/yihuang/0af450e858daf2d99138

**Comment by orangeduck** [comment]
Thanks for the report - I'll check it out.

**Comment by orangeduck** [comment]
I think the main problem here is that if you are parsing from stdin you need to use `mpc_parse_pipe` instead of `mpc_parse_file`. Once I changed that this the parser was working as expected. You should also probably make sure you update to the newest version of `mpc` if you've not already.

You're probably aware already but you have a memory leak in your code. You need to call `mpc_cleanup` with your parsers `Entity`, `Text` and `All` once you are done with them.

I hope that helps.

- Dan

**Comment by yihuang** [comment]
1、Now I've changed `mpc_parse_file` to `mpc_parse_pipe`, it has other problems:

{{{
$ echo 'sdf&sdfds' | ./a.out
>
  text|regex:1:1 'sdf'
  text|regex:1:4 '
'
}}}


2、I didn't know about `mpc_cleanup` before, thanks for reminding.

**Comment by orangeduck** [comment]
This mainly looks like correct behaviour to me. Notice that your rule for `entity` has a semicolon `;` at the end so it didn't manage to match the final `entity` and instead just returned the first `text`. I don't know why it returned another empty `text` node after this but it might be to do with matching the end of the input. I'll investigate.

If you want the parser to error out unless it matches the full input (rather than returning a partial match) you need to include rules for the start and end of input in your grammmar - you can do that by including these as regex for your `all` rule E.G `all : /^/ (<entity> | <text>)* /$/;`.

For the cleanup - you only need to do it once just before your program exists.

**Comment by yihuang** [comment]
But, if I change the text to match any character, I will consume all the rest text. I've updated the gist to show this.
I guess I need to make the text parser not so aggressive, but I can't find the syntax to do it.

**Comment by orangeduck** [comment]
Well your grammar is ambiguous in this case. If you are parsing some kind of html (as it looks like) then & shouldn't exist in text and should only be used for entities so your previous setup was more correct I think. It is hard to say without knowing more about what you are parsing.

Anyway - I don't think this is a bug in mpc so I'm going to close the issue for now. I hope you manage to get your system working.
