### ISSUE TITLE
Maybe there is a BUG when mpca_lang() deals with '\\'.

### ISSUE THREAD

**Issue by zuoxinyu** [orangeduck/mpc#68]
I have a grammar in C-style string:
```
              identifier : /[a-zA-Z0-9_]+/ ;                      
              lambda : '\\' <identifier> '.' <expr> ;             
              application : <lambda> ' ' <expr> ;                 
              expr : <lambda> | <application> | <identifier> ;   
              lizp : /^/ <expr>* /$/ ;                            
```
I want to parse codes like:
```
\x.x y
\x.x \y.y z
...
```
I use this grammar in mpca_lang() with flag `MPCA_LANG_WHITESPACE_SENSITIVE` and generate a binary , the binary will report  "Parser Undefined" error.
I think it's caused by the `'\\'` in the second grammar, so I replace the `'\\'` by another notation.Then it work.
Is this a BUG ? Or how should I do with it ?

**Comment by orangeduck** [comment]
Hi,

To actually parse the backslash character `\` you have to use four backslashes `\\\\`. Here is why:

First - since you are using a C string to represent a single backslash in the string you need to use two `\\`. Then, inside the string you are specifying a character constant using the `''` characters. Inside of this character constant definition a single backslash acts as an escape acharacter so you need two backslashes to represent a single backslash. So to write two backslashes in a C string you need four blackslashes.

Confusing but I hope it makes a little bit of sense.

- Dan

**Comment by zuoxinyu** [comment]
Thanks.
I has just tried then it works now. And this's really a bit confusing. Thank you !
