### ISSUE TITLE
It's not clear that "master" is actually the latest release

### ISSUE THREAD

**Issue by sphynx** [orangeduck/mpc#98]
I wanted to use a stable version of `mpc` to have as few bugs as possible. So, after seeing that "Releases" tab is not empty I went there and downloaded the latest release (0.8.7). However, I've hit a certain bug in that version, so I decided to switch to 'master' branch (which didn't have that bug). Then, I've realised that 0.8.7 version is actually 3 years old and the top of README.md says 'version 0.8.8', so it looks like the master branch is actually the last released version.

I think it would be better if it was explicitly stated somewhere that the 'master' is the last stable version and that people should not use '0.8.7' from 'Releases' or something more concrete about versions.

Thank you!

**Comment by orangeduck** [comment]
Yeah sorry I've been lazy about maintaining the tags. Basically most versions have one or more long standing bugs since there are so many weird edge cases when it comes to parsing. Hopefully if I fix the most recently round of bugs then there will be a stable release I can tag again for you to use.

Thanks!

**Comment by orangeduck** [comment]
I've made the newest version a release. Hopefully there will not be any more bugs in it I've missed!
